### ISSUE TITLE
Request: Add Installation Instruction

### ISSUE THREAD

**Issue by koljapluemer** [2e3s/aw-watcher-media-player#1]
Good morning,

thank you for building this neat looking tool. Maybe I am missing something obvious, but I am not sure how to install this watcher and integrate into AW. Short instructions in the README would be much appreciated.

Cheerz!

**Comment by 2e3s** [comment]
I've added it, what do you think?
I didn't know that it's so awkward for Windows, I think I'll make an installer later when I figure out how.

**Comment by koljapluemer** [comment]
Very neat, thank you!

I'll run through it later and will let you know if I there are any struggles, but I think this issue can be closed :)

**Comment by 2e3s** [comment]
I've also added a windows installer https://github.com/2e3s/aw-watcher-media-player/releases/tag/v1.0.1

**Comment by MarkRenton1** [comment]
Hi, just wanted to inform you that not everyone who lands on the README of your repository, might be familiar with Github (it's directly linked in ActivityWatch's docs https://docs.activitywatch.net/en/latest/watchers.html).
Hence, when they read for Windows "Run the attached installer executable", they might not know where to look (they have to go to a different page, that's not explicitly specified, currently: https://github.com/2e3s/aw-watcher-media-player/releases/tag/v1.1.1).
So I'm of the opinion this could be clarified.

Thank you for the coding

**Comment by 2e3s** [comment]
@MarkRenton1 I agree, thank you, corrected in https://github.com/2e3s/aw-watcher-media-player/commit/d170c56bcc82ca62cbd2efeffc7202c3b86c3d90
