### ISSUE TITLE
Add a index.html vizualisation page to embed in the ActivityWatch's Overview page

### ISSUE THREAD

**Issue by Naereen** [2e3s/aw-watcher-media-player#3]
Hi there again,
I thought it would be better to move this feature request on its proper issue ticket.

What I have in mind would be similar to what is proposed on this other ActivityWatch plugin:
https://github.com/Alwinator/aw-watcher-utilization?tab=readme-ov-file#custom-visualizations

Regards and thanks in advance if you find time to work on that!
I can help testing it, but won't have time to work on it much more sorry.

**Comment by 2e3s** [comment]
I have made the [visualization](https://github.com/2e3s/aw-watcher-media-player#custom-visualization). What do you think?

**Comment by Naereen** [comment]
Hello there @2e3s,
Great job! It looks very nice!
The explanations in the README seem clear and precise enough to me :+1:!

**Comment by 2e3s** [comment]
If you'll try to use this, please close the issue after testing, if it works okay for you, and if you have no more doable suggestions (AW is fairly limited with the custom visualizations). Thanks

**Comment by Naereen** [comment]
It works fine!
![Capture d’écran_2024-04-07_11-37-11](https://github.com/2e3s/aw-watcher-media-player/assets/11994719/cf793b5c-a401-435e-844b-64100fae0802)
Good job!
I'm closing this issue :+1:!!!

**Comment by Naereen** [comment]
Suggestion: in the setup process from AW client webpage, when adding the visualization, it is required to specify "index" I believe, as the second interactive popup window asks something.
Could this detail be added to the documentation in the README, for completeness of the process?

**Comment by 2e3s** [comment]
The second interactive popup window asks something but I thought it's an incomplete functionality of AW UI, so it doesn't make any difference what to write there. At least as I could understand.

**Comment by Naereen** [comment]
OK I see.
