### ISSUE TITLE
Does not detect spt

### ISSUE THREAD

**Issue by 0xbrayo** [2e3s/aw-watcher-media-player#5]
When I play music from [spt](https://github.com/Rigellute/spotify-tui) it is not detected. It does have a media banner in the notifications icon, looks similar to spotify in every way. Idk why it's not detected.

**Comment by 2e3s** [comment]
Hello! It is not actually a media player: https://github.com/Rigellute/spotify-tui#limitations and with a shallow look I don't find any crates in its dependencies which would post the data. So some other media player (spotify client) posts it for your system, I assume (which should be detected by aw-watcher-media-player neverthelesss).

**Comment by 0xbrayo** [comment]
Thanks

**Comment by 0xbrayo** [comment]
Oh yeah, so I guess the issue is with not detecting when [spotifyd](https://github.com/Spotifyd/spotifyd) plays music

**Comment by 0xbrayo** [comment]
what are the crates you were looking out for?

**Comment by 2e3s** [comment]
I have just looked at crates to guess by their names, spt have very few ones. One example would be https://lib.rs/crates/souvlaki

As for spotifyd, as I see there is a feature `dbus_mpris` which suggests the way of posting metadata for Linux. aw-watcher-media-player also uses MPRIS in Linux to read the currently playing media. So I would expect it to work if you don't have extra configuration in `include_players` and `exclude_players` options for aw-watcher-media-player. I can try running it myself later.

**Comment by 0xbrayo** [comment]
I didn't not do any extra config with aw-watcher-media-player. So I guess it should work. Let me know when you get around to running it yourself.

**Comment by 2e3s** [comment]
Just an update, spotifyd seems to report the data, and aw-watcher-media-player reports it, but not very correctly with lags and gaps. I'll look more into this.
As you get nothing at all, it may or may not be related, please try to run it manually with `-vv` and ActivityWatch running and see if there is some error or warning.

**Comment by 0xbrayo** [comment]
My experience is similar to yours somewhat, aw-watcher-media-player would detect a new song, but no data would be captured, it would be just a blank entry with gaps between songs. I switched to [spotify_player](https://github.com/aome510/spotify-player) works great straight of the box.
