### ISSUE TITLE
Startup inconveniences

### ISSUE THREAD

**Issue by mars985** [2e3s/aw-watcher-media-player#9]
1. It doesn't autostart with the rest of the activity watch modules, and every time I have to manually go into the aw tray icon and turn it on. 

- I have tried adding it to the autostart modules in the aw-qt.toml file, but it didn't seem to work.
- I tried installing the with the windows installer. I tried it with the default install path (AppData/Local), and then again into the activity watch folder with the other default modules. I am on windows 11 22H2 if that helps.
- I tried adding the executable to startup, but it just opens up a blank command prompt window, so I don't think that's how you launch it.

2. When my PC wakes up from sleep and I had the media-player module turned on, sometimes it turns back off and I have to turn it on again.

Other than these, it works perfectly. Do I need to edit something in a config file somewhere? I'm happy to provide any other details that you might need.

**Comment by 2e3s** [comment]
Hello! Could you give the content of your `aw-qt.toml` with the specified module in it, please?
Also, please show an output of `echo %PATH%` in your Windows terminal.

**Comment by 2e3s** [comment]
> Also, please show an output of `echo %PATH%` in your Windows terminal

I mean, I just wanted to check if the folder is present there. Windows installer has an [instruction](https://github.com/2e3s/aw-watcher-media-player/blob/main/windows.nsi#L16) to change PATH, but I've just realized that it is alright if you have this option
> manually go into the aw tray icon and turn it on.

So, most likely something is not right with `aw-qt.toml`. I would improve the installation section in readme if we figure it out.

**Comment by mars985** [comment]
AppData\Local\activitywatch\activitywatch\aw-qt\aw-qt.toml
```
[aw-qt]
#autostart_modules = ["aw-server", "aw-watcher-afk", "aw-watcher-window", "aw-watcher-media-player"]

[aw-qt-testing]
#autostart_modules = ["aw-server", "aw-watcher-afk", "aw-watcher-window"]
```

echo %PATH%
```
C:\Users\Admin\AppData\Local\aw-watcher-media-player;C:\Users\Admin\AppData\Local\activitywatch\activitywatch\aw-watcher-media-player
```

**Comment by 2e3s** [comment]
I think you might've missed `#` in the beginning of the line which comments the line, the proper content is
```toml
[aw-qt]
autostart_modules = ["aw-server", "aw-watcher-afk", "aw-watcher-window", "aw-watcher-media-player"]
```

**Comment by mars985** [comment]
You're right! It works after i removed the `#`. I don't know if I somehow added that or if it was commented out by default. But anyway, thanks so much!
